//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int collectId { get; set; }
        public int rId { get; set; }
        public int rider { get; set; }
        public string foodName { get; set; }
        public System.DateTime timeRemained { get; set; }
        public string status { get; set; }
    
        public virtual Detail Details1 { get; set; }
        public virtual Detail Detail1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
