//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oId { get; set; }
        public string foodName { get; set; }
        public System.DateTime prsrvTime { get; set; }
        public Nullable<int> rId { get; set; }
        public string orderStatus { get; set; }
        public byte[] placeTime { get; set; }
        public Nullable<int> riderId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
